# Setup
title:               Florsti
tagline:             'A Jekyll theme'
description:         'A nice website for me'
url:                 https://portfolio.rolfs-design.nl
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Rolfs Design
  url:               https://twitter.com/florsti
  email:             rolf.vr@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
